steps:
# - name: 'gcr.io/cloud-builders/git'
#   args: ['clone', 'https://bitbucket.org/innovobuilders/notification-service.git']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/innovo-app/innovo_builder_microservice_notification:latest", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/innovo-app/innovo_builder_microservice_notification:latest"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'replace'
    - '-f'
    - 'notification-service-web-deployment.yaml'
    - '-f'
    - 'notification-service-web-service.yaml'
    - '--force'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=innovo-builders-cluster'

