apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose.yaml convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: notification-service-web
  name: notification-service-web
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8000
  selector:
    io.kompose.service: notification-service-web
  type: LoadBalancer  
status:
  loadBalancer: {}
